sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9.0'
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install --save-dev solidity-coverage
  - npm install
before_script:
  - npm run testrpc -i 666 --gasLimit 0xfffffffffff --gasPrice 100000000000 > /dev/null &
  # - sleep 5
script:
  - truffle test
 after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
